site_name: Jose Blanca
site_description: Página personal de Jose Blanca
site_author: Jose Blanca
copyright: © 2021-2023, Jose Blanca
nav:
  - "sobre mí": index.md
  - Cursos y seminarios: edu/index.md
  - Filosofía de la ciencia:
    - el oficio de la duda:
      - 'sobre el oficio de la duda': phi_sci/el_oficio_de_la_duda/index.md
      - 'leer en la web': phi_sci/el_oficio_de_la_duda/leer/prefacio.html
    - 'a ciencia cierta': phi_sci/a_ciencia_cierta/index.md
  - Genética en a ciencia cierta: genetica/a_ciencia_cierta/index.md
  - Laboratorio: https://bioinfcomav.github.io/
  - Youtube: 'https://www.youtube.com/channel/UC7-bjPuStqjJqbDiv0pTI5g'
  - GitHub: https://github.com/JoseBlanca/
  - Rincones de interés: rincones.md
  - Zen el explorador racional: zen_del_explorador_racional.md

theme:
  name: material
  features:
    - navigation.sections
  language: es
markdown_extensions:
  - attr_list
copyright: Copyright &copy; Jose Blanca
extra:
  social:
    - icon: fontawesome/brands/youtube
      link: 'https://www.youtube.com/channel/UC7-bjPuStqjJqbDiv0pTI5g'
      name: Jose Blanca en Youtube
  generator: false
  analytics:
    provider: google
    property: G-XYPCFE15R4
plugins: []
